<?php

/*function cookieskipaccess_admin() {

  $form['cookieskipaccess_message'] = array(
    '#type'=>'textarea',
    '#default_value'=> variable_get('cookieskipaccess_message','Control to some fields has been controlled due to: <br>!reason.</br>Please click here <a href="!url">here</a> to see them.'),
    '#title'=>t('Message'),
    '#description'=>t("Message to display"),
  );
  return system_settings_form($form);
}*/